### ISSUE TITLE
Abixen Core - Failed to start

### ISSUE THREAD

**Issue by alvin-reyes** [abixen/abixen-platform#273]
Anyone encountered this issue when trying to run the abixen-platform-core?

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target com.abixen.platform.core.configuration.properties.PlatformMailConfigurationProperties@55691a59 failed:

    Property: platform.core.mail.outgoing.host
    Value: null
    Reason: may not be null

    Property: platform.core.mail.outgoing.user
    Value: null
    Reason: may not be null

    Property: platform.core.mail.outgoing.smtp
    Value: null
    Reason: may not be null

    Property: platform.core.mail.outgoing.transport
    Value: null
    Reason: may not be null

    Property: platform.core.mail.outgoing.debug
    Value: null
    Reason: may not be null

    Property: platform.core.mail.outgoing.port
    Value: null
    Reason: may not be null


Action:

Update your application's configuration

```
I can always put the default values to proceed but is this expected?
